---
title: "Urban-rural comparison"
format: html
---


```{r}
library(tidyverse)
library(levante) 
```


```{r}
dataset_spec <- list(list(name = "pilot_uniandes_co_rural_processed:bxgv:v1_0", 
                          version = "current"),
                     list(name = "pilot_uniandes_co_bogota_processed:d0c5:v1_0", 
                          version = "current")) 
                     
# table = dataset.table("runs:8fp9")
# table = dataset.table("runs_scored:6bsc")

scores <- levante::get_scores(dataset_spec) |>
  mutate(dataset_name = ifelse(dataset == "pilot_uniandes_co_rural_processed:bxgv:v3_0", 
                               "rural", "bogota"))

```

ROAR cleanup

```{r}
scores$task_id <- str_replace(scores$task_id, "-es", "")

scores <- filter(scores, age > 5, age < 13)
```

Tasks with standard scores.

```{r}
ggplot(filter(scores, !(task_id %in% c("pa","sre",
                                       "same-different-selection","theory-of-mind"))),
       aes(x = age, y = score, col = dataset_name)) + 
  geom_point(alpha = .1) + 
  geom_smooth(method = "lm") + 
  facet_wrap(~task_id, scales = "free_y") + 
  theme_classic() + 
  ggthemes::scale_color_solarized(name = "Region") + 
  theme(legend.position = "bottom") 
```
ROAR tasks without standard scores.

```{r}
ggplot(filter(scores, task_id %in% c("pa","sre")),
       aes(x = age, y = score, col = dataset)) + 
  geom_point(alpha = .1) + 
  geom_smooth(method = "lm") + 
  facet_wrap(~task_id, scales = "free_y") + 
  theme_classic() + 
  ggthemes::scale_color_solarized() + 
  theme(legend.position = "bottom") 
```
